# Generated by Django 4.0.6 on 2025-05-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('staff_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('staff_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_original', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('kinopoisk_id', models.IntegerField()),
                ('kinopoisk_url', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('poster', models.ImageField(upload_to='premieres/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('countries', models.ManyToManyField(related_name='movies_country', to='moviepremieres.country')),
                ('directors', models.ManyToManyField(related_name='movies_director', to='moviepremieres.director')),
                ('genres', models.ManyToManyField(related_name='movies_genre', to='moviepremieres.genre')),
                ('writers', models.ManyToManyField(related_name='movies_writer', to='moviepremieres.writer')),
            ],
        ),
    ]
