# Generated by Django 4.0.6 on 2025-05-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepremieres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='premiere_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
