# Generated by Django 4.0.6 on 2025-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
