# Generated by Django 4.0.6 on 2025-02-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_telegram_connected_profile_telegram_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
