# Generated by Django 4.0.6 on 2025-03-13 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0006_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointshistory',
            name='target_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='pointshistory',
            name='target_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
