# Generated by Django 4.0.6 on 2025-04-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
