# Generated by Django 4.0.6 on 2024-09-26 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_original', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('director', models.CharField(max_length=200)),
                ('kinopoisk_id', models.IntegerField()),
                ('kinopoisk_url', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('url', models.URLField(max_length=2000)),
                ('poster', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movies_add', to=settings.AUTH_USER_MODEL)),
                ('users_dislike', models.ManyToManyField(blank=True, related_name='movies_dislike', to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='movies_like', to=settings.AUTH_USER_MODEL)),
                ('users_watched', models.ManyToManyField(blank=True, related_name='movies_watched', to=settings.AUTH_USER_MODEL)),
                ('users_watchlist', models.ManyToManyField(blank=True, related_name='movies_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-created'], name='movies_movi_created_4f7274_idx'),
        ),
    ]
