# Generated by Django 4.0.6 on 2024-09-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_country_director_genre_writer_remove_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_staff_json',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
