# Generated by Django 4.0.6 on 2024-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_movie_staff_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_json',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
