# Generated by Django 4.0.6 on 2024-12-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_movie_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
