# Generated by Django 4.0.6 on 2024-12-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_total_likes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-total_likes'], name='movies_movi_total_l_630f61_idx'),
        ),
    ]
