# Generated by Django 4.0.6 on 2025-01-03 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_movie_movies_movi_total_l_630f61_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='users_dislike',
            field=models.ManyToManyField(blank=True, related_name='movies_dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
