# Generated by Django 4.0.6 on 2025-01-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-total_dislikes'], name='movies_movi_total_d_ef4bf1_idx'),
        ),
    ]
