# Generated by Django 4.0.6 on 2025-01-25 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0012_movielist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='liked_movie_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
