# Generated by Django 4.0.6 on 2025-01-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movielist_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_original',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
