# Generated by Django 4.0.6 on 2025-02-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_movie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type_movie',
            field=models.CharField(choices=[('FILM', 'Film'), ('TV_SERIES', 'TV Series')], default='FILM', max_length=10),
        ),
    ]
