# Generated by Django 4.0.6 on 2025-03-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-total_views'], name='movies_movi_total_v_d128da_idx'),
        ),
    ]
