# Generated by Django 4.0.6 on 2025-03-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_movie_total_views_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieList',
        ),
    ]
